# Guacamole server configuration
guacd-hostname: gloria-guacd
guacd-port: 4822

# Authentication
auth-provider: net.sourceforge.guacamole.net.auth.noauth.NoAuthenticationProvider

# Use basic XML user mapping for simplicity
user-mapping: /etc/guacamole/user-mapping.xml

# Skip login screen
skip-if-unavailable: mysql, postgresql, ldap
